export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const READ_TEMP_STARTED = 'READ_TEMP_STARTED';
export const READ_TEMP_SUCCEEDED = 'READ_TEMP_SUCCEEDED';
export const READ_TEMP_FAILED = 'READ_TEMP_FAILED';

export const READ_PUMP_STARTED = 'READ_PUMP_STARTED';
export const READ_PUMP_SUCCEEDED = 'READ_PUMP_SUCCEEDED';
export const READ_PUMP_FAILED = 'READ_PUMP_FAILED';

export const READ_HEATER_STARTED = 'READ_HEATER_STARTED';
export const READ_HEATER_SUCCEEDED = 'READ_HEATER_SUCCEEDED';
export const READ_HEATER_FAILED = 'READ_HEATER_FAILED';

export const READ_BREWSESSION_STARTED = 'READ_BREWSESSION_STARTED';
export const READ_BREWSESSION_SUCCEEDED = 'READ_BREWSESSION_SUCCEEDED';
export const READ_BREWSESSION_FAILED = 'READ_BREWSESSION_FAILED';

export const BREWSESSION_STARTSTOP_STARTED = 'BREWSESSION_STARTSTOP_STARTED';
export const BREWSESSION_STARTSTOP_SUCCEEDED = 'BREWSESSION_STARTSTOP_SUCCEEDED';
export const BREWSESSION_STARTSTOP_FAILED = 'BREWSESSION_STARTSTOP_FAILED';

export const READ_BREWSESSION_DATA_STARTED = 'READ_BREWSESSION_DATA_STARTED';
export const READ_BREWSESSION_DATA_SUCCEEDED = 'READ_BREWSESSION_DATA_SUCCEEDED';
export const READ_BREWSESSION_DATA_FAILED = 'READ_BREWSESSION_DATA_FAILED';

export const UPDATE_BREWSESSIONSTATUS_FIELD = 'UPDATE_BREWSESSIONSTATUS_FIELD';