export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

export const READ_TEMP_SENSOR = 'READ_TEMP_SENSOR';

export const READ_TEMP_STARTED = 'READ_TEMP_STARTED';
export const READ_TEMP_SUCCEEDED = 'READ_TEMP_SUCCEEDED';
export const READ_TEMP_FAILED = 'READ_TEMP_FAILED';
